# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          HwangTaehyun
baseurl:        ""
url:            "https://hwangtaehyun.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Taehyun Hwang
  url:          https://HwangTaehyun.github.io
  email:        eeht1717@gmail.com
  github:       HwangTaehyun
  twitter:      kkk

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/HwangTaehyun/HwangTaehyun.github.io
